### ISSUE TITLE
How to calculate the values the convolution kernel?

### ISSUE THREAD

**Issue by shehzi-khan** [tvganesh/deconvlucy#1]
Hi Ganesh,

I'm looking for a deblurring method to reduce motion blur in my image, which contains simple geometrical shapes drawn in black color on a white paper. When I move the paper while holding it in my hand, the motion blur is introduced. I saw your code for deconvlucy.cpp but **I couldn't understand how did you calculate the values of convolution kernel**. Is it relative to speed of motion, distance from camera or something else? 
Since I'm moving the object with my hand, so speed and distance may vary.

Thanks,

**Comment by tvganesh** [comment]
Hi - It is a long time since I did this. I don't quite recall now. You may have to check it out in  the net, I guess - Ganesh
